# Generated by Factory Steps v0.1.0
#
module FactoryStepsHelpers

  def model_class(name)
    dehumanize(name).classify.constantize
  end

  def get_current_object_for(model)
    object = instance_variable_get("@current_#{dehumanize(model)}")
    raise "Object missing or not loaded" unless object
    object
  end

  def set_current_object_for(model, attributes_or_object={})
    object = attributes_or_object.is_a?(Hash) ? model_class(model).make(attributes_or_object) : attributes_or_object
    instance_variable_set("@current_#{dehumanize(model)}", object)
  end

  def dehumanize(string)
    string.to_s.underscore.downcase.gsub(/ +/,'_').gsub('"','')
  end

end

World(FactoryStepsHelpers)
